[package]
name = "facet-json"
version = "0.1.15"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "JSON serialization and deserialization support for Facet traits"
keywords = ["facet", "json", "serialization", "deserialization"]
categories = ["encoding", "development-tools"]

[dependencies]
facet = { path = "../facet", version = "0.1.18", features = ["reflect"] }
log = "0.4.27"

[dev-dependencies]
facet = { path = "../facet", version = "0.1.18", features = [
    "reflect",
    "derive",
] }
color-backtrace = "0.7.0"
ctor = "0.4.1"
env_logger = "0.11.8"
