[package]
name = "facet-jsonschema"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
facet-core = { version = "0.11.0", path = "../facet-core" }
facet-reflect = { version = "0.10.4", path = "../facet-reflect" }
facet = { path = "../facet" }

[dev-dependencies]
serde_json = "1.0"
schemars = { version = "0.8" }