[workspace]
members = [
    # core
    "facet-core",
    "facet",

    # derive macro
    "facet-derive-parse",
    "facet-derive-emit",
    "facet-derive",

    # reflection
    "facet-reflect",

    # dev helpers
    "facet-dev",

    # test helpers
    "facet-testhelpers",

    # formats / ecosystem
    "facet-args",
    "facet-json",
    "facet-msgpack",
    "facet-pretty",
    "facet-toml",
    "facet-kdl",
    "facet-urlencoded",
    "facet-yaml",
    "facet-jsonschema",
]
exclude = ["outside-workspace"]
resolver = "3"

[workspace.package]
version = "0.15.0"
authors = ["Amos Wenger <amos@bearcove.eu>"]
edition = "2024"
rust-version = "1.86.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/facet-rs/facet"
