[package]
name = "measure-bloat"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "measure-bloat"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
toml_edit = "0.22"
indicatif = "0.17.11"
