[package]
name = "measure-bloat"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "measure-bloat"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
toml_edit = "0.22"
indicatif = "0.17.11"
owo-colors = "4.2.1"
color-backtrace = "0.6"
pathdiff = "0.2.3"
log = "0.4.27"
itertools = "0.14.0"
tempfile = "3.20.0"
