[package]
name = "facet"
version = "0.1.10"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Re-exports the Facet trait and derive macros, along with Shape and all related types"
keywords = ["facet", "introspection", "reflection"]
categories = ["development-tools"]

[dependencies]
facet-core.workspace = true
facet-derive.workspace = true

[features]
# Does nothing, only used for tests
testfeat = []
std = ["facet-core/std"]
default = ["std"]
