[package]
name = "ks-facet"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ks-facet-json-read = { version = "0.1.0", path = "../ks-facet-json-read" }
ks-facet-json-write = { version = "0.1.0", path = "../ks-facet-json-write" }
ks-facet-pretty = { version = "0.1.0", path = "../ks-facet-pretty" }
ks-mock = { version = "0.1.0", path = "../ks-mock" }
