[package]
name = "facet-msgpack"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "MessagePack serialization and deserialization for Facet types"
keywords = [
    "msgpack",
    "serialization",
    "deserialization",
    "reflection",
    "facet",
]
categories = ["encoding", "parsing", "data-structures"]

[dependencies]
log = "0.4.27"
facet = { path = "../facet", version = "0.1.18", features = ["reflect"] }

[dev-dependencies]
color-backtrace = "0.7.0"
ctor = "0.4.1"
facet = { path = "../facet", version = "0.1.18", features = [
    "reflect",
    "derive",
] }
