[package]
name = "facet-pretty"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Pretty-printing for types implementing the Facet trait"
keywords = [
    "pretty-print",
    "formatting",
    "reflection",
    "serialization",
    "visualization",
]
categories = ["development-tools", "visualization", "command-line-utilities"]

[dependencies]
facet-core = { path = "../facet-core", version = "0.4.2" }
facet-peek = { path = "../facet-peek", version = "0.2.14" }

[dev-dependencies]
facet-derive = { path = "../facet-derive", version = "0.1.17" }