[package]
name = "facet-pretty"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Pretty-printing for types implementing the Facet trait"
keywords = [
    "pretty-print",
    "formatting",
    "reflection",
    "serialization",
    "visualization",
]
categories = ["development-tools", "visualization", "command-line-utilities"]

[dependencies]
facet = { path = "../facet", version = "0.1.18", features = ["reflect"] }

[dev-dependencies]
facet = { path = "../facet", version = "0.1.18", features = [
    "reflect",
    "derive",
] }
