name: Binary Size Analysis

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  bloat-check:
    runs-on: depot-ubuntu-24.04-16

    container:
      image: ghcr.io/facet-rs/facet-ci:latest-amd64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ✨ Configure git safe directory
        shell: bash
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - uses: Swatinem/rust-cache@v2

      - name: ✨ Install cargo-bloat and cargo-llvm-lines
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-bloat,cargo-llvm-lines

      - name: ✨ Build and analyze PR branch
        shell: bash
        run: |
          cargo build --release --manifest-path outside-workspace/bigapi-cli-facet/Cargo.toml
          cargo bloat --release --manifest-path outside-workspace/bigapi-cli-facet/Cargo.toml -n 30 > pr-bloat.txt
          cargo bloat --release --manifest-path outside-workspace/bigapi-cli-facet/Cargo.toml --crates -n 30 > pr-bloat-crates.txt
          
          # LLVM lines analysis
          cargo llvm-lines --release --manifest-path outside-workspace/bigapi-types-facet/Cargo.toml | head -30 > pr-llvm-lines-types.txt
          cargo llvm-lines --release --manifest-path outside-workspace/bigapi-indirection-facet/Cargo.toml | head -30 > pr-llvm-lines-indirection.txt

      - name: ✨ Checkout main branch
        shell: bash
        run: |
          # Stash any changes (like Cargo.lock files) before switching branches
          git stash --include-untracked
          git checkout main
          # Re-apply the changes (path dependencies) after switching
          git stash pop || true

      - name: ✨ Build and analyze main branch
        shell: bash
        run: |
          cargo build --release --manifest-path outside-workspace/bigapi-cli-facet/Cargo.toml
          cargo bloat --release --manifest-path outside-workspace/bigapi-cli-facet/Cargo.toml -n 30 > main-bloat.txt
          cargo bloat --release --manifest-path outside-workspace/bigapi-cli-facet/Cargo.toml --crates -n 30 > main-bloat-crates.txt
          
          # LLVM lines analysis
          cargo llvm-lines --release --manifest-path outside-workspace/bigapi-types-facet/Cargo.toml | head -30 > main-llvm-lines-types.txt
          cargo llvm-lines --release --manifest-path outside-workspace/bigapi-indirection-facet/Cargo.toml | head -30 > main-llvm-lines-indirection.txt

      - name: ✨ Generate comparison
        shell: bash
        run: |
          echo "## 📊 Binary Size Analysis" > bloat-report.md
          echo "" >> bloat-report.md
          echo "Comparison of binary sizes between \`main\` and this PR:" >> bloat-report.md
          echo "" >> bloat-report.md
          
          # Extract total size from both files (from the last line)
          MAIN_SIZE=$(grep "\.text section size" main-bloat.txt | awk '{print $3}')
          PR_SIZE=$(grep "\.text section size" pr-bloat.txt | awk '{print $3}')
          
          # Calculate the difference
          MAIN_BYTES=$(echo $MAIN_SIZE | sed 's/[^0-9.]//g')
          PR_BYTES=$(echo $PR_SIZE | sed 's/[^0-9.]//g')
          if [[ $MAIN_SIZE == *"MiB"* ]]; then
            MAIN_BYTES=$(echo "$MAIN_BYTES * 1048576" | bc | cut -d'.' -f1)
          elif [[ $MAIN_SIZE == *"KiB"* ]]; then
            MAIN_BYTES=$(echo "$MAIN_BYTES * 1024" | bc | cut -d'.' -f1)
          fi
          if [[ $PR_SIZE == *"MiB"* ]]; then
            PR_BYTES=$(echo "$PR_BYTES * 1048576" | bc | cut -d'.' -f1)
          elif [[ $PR_SIZE == *"KiB"* ]]; then
            PR_BYTES=$(echo "$PR_BYTES * 1024" | bc | cut -d'.' -f1)
          fi
          
          DIFF_BYTES=$((PR_BYTES - MAIN_BYTES))
          if [ $DIFF_BYTES -gt 0 ]; then
            DIFF_SIGN="+"
            DIFF_EMOJI="📈"
          elif [ $DIFF_BYTES -lt 0 ]; then
            DIFF_SIGN=""
            DIFF_EMOJI="📉"
          else
            DIFF_SIGN=""
            DIFF_EMOJI="✅"
          fi
          
          # Format the difference
          if [ $DIFF_BYTES -ne 0 ]; then
            ABS_DIFF=${DIFF_BYTES#-}
            if [ $ABS_DIFF -gt 1048576 ]; then
              DIFF_FMT="${DIFF_SIGN}$(echo "scale=2; $DIFF_BYTES / 1048576" | bc) MiB"
            elif [ $ABS_DIFF -gt 1024 ]; then
              DIFF_FMT="${DIFF_SIGN}$(echo "scale=2; $DIFF_BYTES / 1024" | bc) KiB"
            else
              DIFF_FMT="${DIFF_SIGN}${DIFF_BYTES} B"
            fi
          else
            DIFF_FMT="No change"
          fi
          
          echo "| Branch | Total Size | Difference |" >> bloat-report.md
          echo "|--------|------------|------------|" >> bloat-report.md
          echo "| main   | $MAIN_SIZE | - |" >> bloat-report.md
          echo "| **PR** | **$PR_SIZE** | **${DIFF_EMOJI} ${DIFF_FMT}** |" >> bloat-report.md
          echo "" >> bloat-report.md
          
          # Generate diff
          echo "### Diff (by function)" >> bloat-report.md
          echo '```diff' >> bloat-report.md
          diff -u main-bloat.txt pr-bloat.txt >> bloat-report.md || true
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          
          echo "### Diff (by crate)" >> bloat-report.md
          echo '```diff' >> bloat-report.md
          diff -u main-bloat-crates.txt pr-bloat-crates.txt >> bloat-report.md || true
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          
          echo "### LLVM Lines (bigapi-types-facet)" >> bloat-report.md
          echo '```diff' >> bloat-report.md
          diff -u main-llvm-lines-types.txt pr-llvm-lines-types.txt >> bloat-report.md || true
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          
          echo "### LLVM Lines (bigapi-indirection-facet)" >> bloat-report.md
          echo '```diff' >> bloat-report.md
          diff -u main-llvm-lines-indirection.txt pr-llvm-lines-indirection.txt >> bloat-report.md || true
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          
          echo "<details>" >> bloat-report.md
          echo "<summary>Full outputs</summary>" >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### Main branch (by function)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat main-bloat.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### PR branch (by function)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat pr-bloat.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### Main branch (by crate)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat main-bloat-crates.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### PR branch (by crate)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat pr-bloat-crates.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### Main branch LLVM Lines (bigapi-types-facet)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat main-llvm-lines-types.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### PR branch LLVM Lines (bigapi-types-facet)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat pr-llvm-lines-types.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### Main branch LLVM Lines (bigapi-indirection-facet)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat main-llvm-lines-indirection.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "" >> bloat-report.md
          echo "### PR branch LLVM Lines (bigapi-indirection-facet)" >> bloat-report.md
          echo '```' >> bloat-report.md
          cat pr-llvm-lines-indirection.txt >> bloat-report.md
          echo '```' >> bloat-report.md
          echo "</details>" >> bloat-report.md

      - name: ✨ Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: bloat-report.md
          comment-tag: cargo-bloat-analysis
          mode: upsert