name: Binary Size Analysis

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  bloat-check:
    runs-on: depot-ubuntu-24.04-16

    container:
      image: ghcr.io/facet-rs/facet-ci:latest-amd64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ✨ Configure git safe directory
        shell: bash
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - uses: Swatinem/rust-cache@v2

      - name: ✨ Install cargo-bloat and cargo-llvm-lines
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-bloat,cargo-llvm-lines

      - name: ✨ Build measure-bloat tool
        shell: bash
        run: |
          cd outside-workspace/measure-bloat
          cargo build --release

      - name: ✨ Run binary size analysis
        shell: bash
        run: |
          cd outside-workspace/measure-bloat
          # Run the full comparison which will generate a comprehensive markdown report
          cargo run --release -- compare
          
          # Copy the generated report to the workspace root for artifact upload
          cp bloat-results/comparison_report.md ../../bloat-report.md

      - name: ✨ Save PR info
        run: |
          echo "${{ github.event.pull_request.number }}" > pr-number.txt

      - name: ✨ Upload analysis report
        uses: actions/upload-artifact@v4
        with:
          name: bloat-analysis-report
          path: |
            bloat-report.md
            pr-number.txt
          retention-days: 7