name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  test:
    runs-on: arc-runners
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Install Rust specified toolchain
        run: |
          rustc --version

      - name: Install just and cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-nextest

      - name: Run tests
        shell: bash
        run: |
          just

      - name: Run miri
        shell: bash
        run: |
          just miri
