name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  code-quality:
    runs-on: depot-ubuntu-24.04-arm-16

    container:
      image: ghcr.io/facet-rs/facet-ci:latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Run code quality checks
        shell: bash
        run: |
          just codegen-check
          just rustfmt
          just absolve

  test:
    runs-on: depot-ubuntu-24.04-arm-16

    container:
      image: ghcr.io/facet-rs/facet-ci:latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        shell: bash
        run: |
          just test

  nostd:
    runs-on: depot-ubuntu-24.04-arm-16

    container:
      image: ghcr.io/facet-rs/facet-ci:latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Run nostd tests
        shell: bash
        run: |
          just nostd

  clippy:
    runs-on: depot-ubuntu-24.04-arm-16

    container:
      image: ghcr.io/facet-rs/facet-ci:latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Run clippy
        shell: bash
        run: |
          just clippy

  doc-tests:
    runs-on: depot-ubuntu-24.04-arm-16

    container:
      image: ghcr.io/facet-rs/facet-ci:latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Run doc tests
        shell: bash
        run: |
          just doc-tests

  miri:
    runs-on: depot-ubuntu-24.04-arm-16

    container:
      image: ghcr.io/facet-rs/facet-ci:latest-miri
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Run miri
        shell: bash
        run: |
          export CI=true
          just miri
