name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  test:
    runs-on: arc-runners

    container:
      image: rust:1.86.0-slim
    steps:
      - uses: actions/checkout@v4

      - name: Setup cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Verify Rust version
        run: |
          rustc --version

      - name: Install just and cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-nextest

      - name: Run tests
        shell: bash
        run: |
          just

  miri:
    runs-on: arc-runners

    container:
      image: rustlang/rust:nightly-slim
    steps:
      - uses: actions/checkout@v4

      - name: Setup cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Verify Rust version
        run: |
          rustc --version

      - name: Install just and cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-nextest

      - name: Run miri
        shell: bash
        run: |
          just miri
