[package]
name = "facet-reflect"
version = "0.8.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Allows peeking (reading from) and poking (writing to) types that implement Facet"
keywords = ["reflection", "introspection", "facet", "peek", "poke"]
categories = ["development-tools", "rust-patterns"]

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[dependencies]
bitflags = "2.9.0"
facet-core = { path = "../facet-core", version = "0.8.0" }
log = "0.4.27"
yansi = "1.0.1"

[dev-dependencies]
eyre = "0.6.12"
facet = { path = "../facet" }
facet-samplelibc = { path = "../facet-samplelibc" }
facet-testhelpers = { path = "../facet-testhelpers" }
log = "0.4.27"
tempfile = "3.19.1"
